### ISSUE TITLE
Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by michael-milette** [EduardoKrausME/moodle-local-kopere_dashboard#26]
With debugging set to DEVELOPER mode, I get the following warning at the top of each panel in the Kopere Dashboard:

Warning: Creating default object from empty value in /theme/boost/version.php on line 27

Line 27 refers to the line starts with "$plugin->version...". So basically, at this point, the $plugin variable has not yet been initialized.

**Additional info**

- I am using Moodle 3.6.3 with the Boost theme.
- I am using the open-internal setting - so URL looks like:
/local/kopere_dashboard/open-internal.php?classname=dashboard&method=start
- I am using the latest version of Kopere Dashboard downloaded moments ago.

Let me know if you need any additional information in order to reproduce the issue.

Best regards,

Michael Milette

**Comment by ichikawacraice** [comment]
Same here,

console errors :

`custom.min.js:1 TypeError: $(...).find(...).daterangepicker is not a function
    at startForm (custom.min.js:1)
    at HTMLDocument.<anonymous> (custom.min.js:1)
    at mightThrow (jquery-3.2.1.js:3583)
    at process (jquery-3.2.1.js:3651)
startForm @ custom.min.js:1
custom.min.js:1 TypeError: $(...).find(...).select2 is not a function
    at startForm (custom.min.js:1)
    at HTMLDocument.<anonymous> (custom.min.js:1)
    at mightThrow (jquery-3.2.1.js:3583)
    at process (jquery-3.2.1.js:3651)
startForm @ custom.min.js:1
jquery-3.2.1.js:3860 jQuery.Deferred exception: $(...).find(...).validator is not a function TypeError: $(...).find(...).validator is not a function
    at startForm (https://ead.claudiamatarazzoensina.com.br/local/kopere_dashboard/assets/dashboard/js/custom.min.js:1:1171)
    at HTMLDocument.<anonymous> (https://ead.claudiamatarazzoensina.com.br/local/kopere_dashboard/assets/dashboard/js/custom.min.js:1:14)
    at mightThrow (https://ead.claudiamatarazzoensina.com.br/theme/jquery.php/core/jquery-3.2.1.js:3583:29)
    at process (https://ead.claudiamatarazzoensina.com.br/theme/jquery.php/core/jquery-3.2.1.js:3651:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.2.1.js:3860
jquery-3.2.1.js:3860 jQuery.Deferred exception: $(...).DataTable is not a function TypeError: $(...).DataTable is not a function
    at HTMLDocument.<anonymous> (https://ead.claudiamatarazzoensina.com.br/local/kopere_dashboard/open-internal.php?classname=users&method=dashboard:431:81)
    at mightThrow (https://ead.claudiamatarazzoensina.com.br/theme/jquery.php/core/jquery-3.2.1.js:3583:29)
    at process (https://ead.claudiamatarazzoensina.com.br/theme/jquery.php/core/jquery-3.2.1.js:3651:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.2.1.js:3860
jquery-3.2.1.js:3869 Uncaught TypeError: $(...).find(...).validator is not a function
    at startForm (custom.min.js:1)
    at HTMLDocument.<anonymous> (custom.min.js:1)
    at mightThrow (jquery-3.2.1.js:3583)
    at process (jquery-3.2.1.js:3651)
jquery-3.2.1.js:3869 Uncaught TypeError: $(...).DataTable is not a function
    at HTMLDocument.<anonymous> (open-internal.php?classname=users&method=dashboard:431)
    at mightThrow (jquery-3.2.1.js:3583)
    at process (jquery-3.2.1.js:3651)`

**Comment by eduardokraus** [comment]
resolved
